apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  labels:
    app: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  strategy:
    type: RollingUpdate
    maxSurge: 0
    maxUnavailable: 1
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: psnx/cloudnd-capstone:%TAG%
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub
---
#kubectl expose deployment capstone-deployment --type=LoadBalancer --name=cloudnd-capstone --port=80 --target-port=80
apiVersion: v1
kind: Service
metadata:
  name: capstone
  labels:
    run: cloudnd-capstone
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: capstone
  type: LoadBalancer